### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by xlc** [xlc/chopsticks-web#1]
- [x] XCM support part 1
  - [x] Detect UMP/DMP/HRMP messages and display them
  - [x] Allow dry run with UMP/DMP/HRML messages
- [ ] XCM support part 2
  - [ ] Allow specify parachain / relaychain endpoints and para id
  - [ ] Automatically create new dest chain instance upon detection of XCM and dry run it and display result
- [ ] Generic execution playbook
  - [ ] Allow user to input networks and actions and run them and display the results for each steps
    - action could be
      - dispatch call for a given origin (via scheduler or extrinsic)
      - new block (optionally with a block number)
      - set storage

**Comment by liamaharon** [comment]
> Generic execution playbook

A note that this is important for dry-running fellowship call whitelisting & calls to upgrade chains
